### ISSUE TITLE
Won't install

### ISSUE THREAD

**Issue by ekkis** [MathieuLoutre/nextjs-stripe-elements#1]
I cloned the project on OSX 10.14.6 but `npm i` breaks.  I initially tried on Node 12.16.3 and downgraded all the way to 10.20.1 but still can't get it to build.  it pukes with the output below.  help?

> fsevents@1.1.2 install /Users/ekkis/dev/tst/node_modules/fsevents
> node install

node-pre-gyp ERR! Tried to download(404): https://fsevents-binaries.s3-us-west-2.amazonaws.com/v1.1.2/fse-v1.1.2-node-v64-darwin-x64.tar.gz 
node-pre-gyp ERR! Pre-built binaries not found for fsevents@1.1.2 and node@10.20.1 (node-v64 ABI) (falling back to source compile with node-gyp) 
node-pre-gyp ERR! Tried to download(undefined): https://fsevents-binaries.s3-us-west-2.amazonaws.com/v1.1.2/fse-v1.1.2-node-v64-darwin-x64.tar.gz 
node-pre-gyp ERR! Pre-built binaries not found for fsevents@1.1.2 and node@10.20.1 (node-v64 ABI) (falling back to source compile with node-gyp) 
  SOLINK_MODULE(target) Release/.node
  SOLINK_MODULE(target) Release/.node
  CXX(target) Release/obj.target/fse/fsevents.o
  CXX(target) Release/obj.target/fse/fsevents.o
In file included from ../fsevents.cc:6:
In file included from ../../nan/nan.h:192:
../../nan/nan_maybe_43_inl.h:112:15: error: no member named 'ForceSet' in 'v8::Object'
  return obj->ForceSet(isolate->GetCurrentContext(), key, value, attribs);
         ~~~  ^
In file included from ../fsevents.cc:6:
In file included from ../../nan/nan.h:192:
../../nan/nan_maybe_43_inl.h:112:15: error: no member named 'ForceSet' in 'v8::Object'
  return obj->ForceSet(isolate->GetCurrentContext(), key, value, attribs);
         ~~~  ^
In file included from ../fsevents.cc:6:
../../nan/nan.h:834:18: warning: 'MakeCallback' is deprecated: Use MakeCallback(..., async_context)
      [-Wdeprecated-declarations]
    return node::MakeCallback(
                 ^
/Users/ekkis/Library/Caches/node-gyp/10.20.1/include/node/node.h:176:1: note: 'MakeCallback' has been explicitly
      marked deprecated here
NODE_DEPRECATED("Use MakeCallback(..., async_context)",
^
/Users/ekkis/Library/Caches/node-gyp/10.20.1/include/node/node.h:91:20: note: expanded from macro
      'NODE_DEPRECATED'
    __attribute__((deprecated(message))) declarator
                   ^
In file included from ../fsevents.cc:6:
../../nan/nan.h:834:18: warning: 'MakeCallback' is deprecated: Use MakeCallback(..., async_context)
      [-Wdeprecated-declarations]
    return node::MakeCallback(
                 ^
In file included from ../fsevents.cc:/Users/ekkis/Library/Caches/node-gyp/10.20.1/include/node/node.h6::
176:../../nan/nan.h1::849 :18:note : 'MakeCallback'warning : has been 'MakeCallback'explicitly 
is       markeddeprecated:  deprecatedUse  hereMakeCallback(..., 
async_context)
      [-Wdeprecated-declarations]
    return node::MakeCallback(
NODE_DEPRECATED("Use MakeCallback(..., async_context)",
                 ^
^
/Users/ekkis/Library/Caches/node-gyp/10.20.1/include/node/node.h/Users/ekkis/Library/Caches/node-gyp/10.20.1/include/node/node.h::16991::120::  notenote: : 'MakeCallback'expanded  hasfrom  beenmacro explicitly
      marked 
deprecated here      
'NODE_DEPRECATED'
NODE_DEPRECATED("Use MakeCallback(..., async_context)",
^
    __attribute__((deprecated(message))) declarator
                   ^
/Users/ekkis/Library/Caches/node-gyp/10.20.1/include/node/node.h:91:20: note: expanded from macro
      'NODE_DEPRECATED'
    __attribute__((deprecated(message))) declarator
                   ^
In file included from ../fsevents.cc:6:
../../nan/nan.h:864:18: warning: 'MakeCallback' is deprecated:In file included from  Use../fsevents.cc :MakeCallback(...,6 :
async_context)
../../nan/nan.h      :[-Wdeprecated-declarations]849:
18: warning: 'MakeCallback' is     return node::MakeCallback(deprecated:
 Use                 ^ 
MakeCallback(..., async_context)
      [-Wdeprecated-declarations]/Users/ekkis/Library/Caches/node-gyp/10.20.1/include/node/node.h
:162:1: note: 'MakeCallback' has    return node::MakeCallback( 
been                  ^explicitly

      marked deprecated here/Users/ekkis/Library/Caches/node-gyp/10.20.1/include/node/node.h
:169:1: note: 'MakeCallback' has been explicitly
      markedNODE_DEPRECATED("Use MakeCallback(..., async_context)", 
deprecated ^here

/Users/ekkis/Library/Caches/node-gyp/10.20.1/include/node/node.h:91:20: note: expanded from macroNODE_DEPRECATED("Use MakeCallback(..., async_context)",

      'NODE_DEPRECATED'^

/Users/ekkis/Library/Caches/node-gyp/10.20.1/include/node/node.h:91:20: note:     __attribute__((deprecated(message))) declaratorexpanded
 from                   ^ 
macro
      'NODE_DEPRECATED'
    __attribute__((deprecated(message))) declarator
                   ^
In file included from ../fsevents.cc:6:
../../nan/nan.h:864:18: warning: 'MakeCallback' is deprecated: Use MakeCallback(..., async_context)
      [-Wdeprecated-declarations]
    return node::MakeCallback(
                 ^
/Users/ekkis/Library/Caches/node-gyp/10.20.1/include/node/node.h:162:1: note: 'MakeCallback' has been explicitly
      marked deprecated here
NODE_DEPRECATED("Use MakeCallback(..., async_context)",
^
/Users/ekkis/Library/Caches/node-gyp/10.20.1/include/node/node.h:91:20: note: expanded from macro
      'NODE_DEPRECATED'
    __attribute__((deprecated(message))) declarator
                   ^
In file included from ../fsevents.cc:6:
../../nan/nan.h:1473:31: warning: 'MakeCallback' is deprecated: Use MakeCallback(..., async_context)
      [-Wdeprecated-declarations]
    return scope.Escape(node::MakeCallback(
                              ^
/Users/ekkis/Library/Caches/node-gyp/10.20.1/include/node/node.h:176:1: note: 'MakeCallback' has been explicitly
      marked deprecated here
NODE_DEPRECATED("Use MakeCallback(..., async_context)",
^
/Users/ekkis/Library/Caches/node-gyp/10.20.1/include/node/node.h:91:20: note: expanded from macro
      'NODE_DEPRECATED'
    __attribute__((deprecated(message))) declarator
                   ^
In file included from ../fsevents.cc:6:
../../nan/nan.h:1473:31: warning: 'MakeCallback' is deprecated: Use MakeCallback(..., async_context)
      [-Wdeprecated-declarations]
    return scope.Escape(node::MakeCallback(
                              ^
/Users/ekkis/Library/Caches/node-gyp/10.20.1/include/node/node.h:176:1: note: 'MakeCallback' has been explicitly
      marked deprecated here
NODE_DEPRECATED("Use MakeCallback(..., async_context)",
^
/Users/ekkis/Library/Caches/node-gyp/10.20.1/include/node/node.h:91:20: note: expanded from macro
      'NODE_DEPRECATED'
    __attribute__((deprecated(message))) declarator
                   ^
4 warnings and 1 error generated.
4 warnings and 1 error generated.
make: make: *** [Release/obj.target/fse/fsevents.o] Error 1*** [Release/obj.target/fse/fsevents.o] Error 1

gypgyp  ERR! build errorERR! 
 build error 
gyp gypERR!  stackERR! Error: `make` failed with exit code: 2
 gypstack  Error: `make` failed with exit code: 2
ERR!gyp  stackERR!     at ChildProcess.onExit (/Users/ekkis/.nvm/versions/node/v10.20.1/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:191:23)
 gypstack      at ChildProcess.onExit (/Users/ekkis/.nvm/versions/node/v10.20.1/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:191:23)
ERR!gyp  stackERR!     at ChildProcess.emit (events.js:198:13)
 gypstack      at ChildProcess.emit (events.js:198:13)
ERR!gyp  stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:248:12)
ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:248:12)
gyp gypERR!  SystemERR! Darwin 18.7.0
 System Darwin 18.7.0
gypgyp ERR!  commandERR!  "/Users/ekkis/.nvm/versions/node/v10.20.1/bin/node" "/Users/ekkis/.nvm/versions/node/v10.20.1/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "build" "--fallback-to-build" "--module=/Users/ekkis/dev/tst/node_modules/fsevents/lib/binding/Release/node-v64-darwin-x64/fse.node" "--module_name=fse" "--module_path=/Users/ekkis/dev/tst/node_modules/fsevents/lib/binding/Release/node-v64-darwin-x64"
command "/Users/ekkis/.nvm/versions/node/v10.20.1/bin/node" "/Users/ekkis/.nvm/versions/node/v10.20.1/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "build" "--fallback-to-build" "--module=/Users/ekkis/dev/tst/node_modules/fsevents/lib/binding/Release/node-v64-darwin-x64/fse.node" "--module_name=fse" "--module_path=/Users/ekkis/dev/tst/node_modules/fsevents/lib/binding/Release/node-v64-darwin-x64"
gyp gypERR!  cwdERR! /Users/ekkis/dev/tst/node_modules/fsevents
 cwdgyp /Users/ekkis/dev/tst/node_modules/fsevents
 gypERR!  node -vERR! v10.20.1
 node -vgyp v10.20.1
 gypERR!  node-gyp -vERR! v5.1.0
 node-gyp -vgyp v5.1.0
 gypERR!  not okERR! 
 not ok 
node-pre-gyp ERR! build error 
node-pre-gyp ERR! stack Error: Failed to execute '/Users/ekkis/.nvm/versions/node/v10.20.1/bin/node /Users/ekkis/.nvm/versions/node/v10.20.1/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --module=/Users/ekkis/dev/tst/node_modules/fsevents/lib/binding/Release/node-v64-darwin-x64/fse.node --module_name=fse --module_path=/Users/ekkis/dev/tst/node_modules/fsevents/lib/binding/Release/node-v64-darwin-x64' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/Users/ekkis/dev/tst/node_modules/fsevents/node_modules/node-pre-gyp/lib/util/compile.js:83:29)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:198:13)
node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:982:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:259:5)
node-pre-gyp ERR! System Darwin 18.7.0
node-pre-gyp ERR! command "/Users/ekkis/.nvm/versions/node/v10.20.1/bin/node" "/Users/ekkis/dev/tst/node_modules/fsevents/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd /Users/ekkis/dev/tst/node_modules/fsevents
node-pre-gyp ERR! node -v v10.20.1
node-pre-gyp ERR! node-pre-gyp -v v0.6.36
node-pre-gyp ERR! not ok 
Failed to execute '/Users/ekkis/.nvm/versions/node/v10.20.1/bin/node /Users/ekkis/.nvm/versions/node/v10.20.1/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --module=/Users/ekkis/dev/tst/node_modules/fsevents/lib/binding/Release/node-v64-darwin-x64/fse.node --module_name=fse --module_path=/Users/ekkis/dev/tst/node_modules/fsevents/lib/binding/Release/node-v64-darwin-x64' (1)

> uglifyjs-webpack-plugin@0.4.6 postinstall /Users/ekkis/dev/tst/node_modules/uglifyjs-webpack-plugin
> node lib/post_install.js

npm WARN nextjs-stripe-elements@1.0.0 No repository field.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.1.2 (node_modules/fsevents):
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.1.2 install: `node install`
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: Exit status 1

added 713 packages from 481 contributors and audited 5259 packages in 17.995s
found 671 vulnerabilities (228 low, 33 moderate, 409 high, 1 critical)
  run `npm audit fix` to fix them, or `npm audit` for details

**Comment by ekkis** [comment]
the problem was with some old version of `fsevents`.  basically I had to:
```bash
# npm uninstall fsevents
# npm install fsevents
# rm package-lock.json
# npm install
```
and that solved it
