### ISSUE TITLE
Won't run

### ISSUE THREAD

**Issue by ekkis** [MathieuLoutre/nextjs-stripe-elements#2]
having managed to install it, now that I run it I get the error below, when visiting the website:

> window is not defined
> ReferenceError: window is not defined
>     at new Provider (/Users/ekkis/dev/tst/node_modules/react-stripe-elements/lib/components/Provider.js:35:5)
>     at processChild (/Users/ekkis/dev/tst/node_modules/react-dom/cjs/react-dom-server.node.development.js:2995:14)
>     at resolve (/Users/ekkis/dev/tst/node_modules/react-dom/cjs/react-dom-server.node.development.js:2960:5)
>     at ReactDOMServerRenderer.render (/Users/ekkis/dev/tst/node_modules/react-dom/cjs/react-dom-server.node.development.js:3435:22)
>     at ReactDOMServerRenderer.read (/Users/ekkis/dev/tst/node_modules/react-dom/cjs/react-dom-server.node.development.js:3373:29)
>     at renderToString (/Users/ekkis/dev/tst/node_modules/react-dom/cjs/react-dom-server.node.development.js:3988:27)    
>     at renderPage (/Users/ekkis/dev/tst/node_modules/next/dist/server/render.js:174:26)
>     at Function.getInitialProps (/Users/ekkis/dev/tst/node_modules/next/dist/server/document.js:83:25)
>     at _callee$ (/Users/ekkis/dev/tst/node_modules/next/dist/lib/utils.js:36:30)
>     at tryCatch (/Users/ekkis/dev/tst/node_modules/regenerator-runtime/runtime.js:65:40)

**Comment by ekkis** [comment]
the issue here is this project is really old and needs its dependencies updated
